export { default as Button } from './Button';
export { default as ErrorMessage } from './ErrorMessage';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Input } from './Input';
export { default as Nav } from './Nav';
export { default as OptimizedImage } from './OptimizedImage';
export { default as SocialsIcons } from './SocialsIcons';
export { default as Title } from './Title';
